/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalId = IDL.Nat;
export const Status = IDL.Variant({
  'ProfitBooked' : IDL.Null,
  'Active' : IDL.Null,
  'Expired' : IDL.Null,
});
export const Strategy = IDL.Variant({
  'OI' : IDL.Null,
  'PCR' : IDL.Null,
  'RSI' : IDL.Null,
  'MACD' : IDL.Null,
  'News' : IDL.Null,
  'Volume' : IDL.Null,
  'Bollinger' : IDL.Null,
});
export const OptionType = IDL.Variant({ 'CE' : IDL.Null, 'PE' : IDL.Null });
export const Time = IDL.Int;
export const Signal = IDL.Record({
  'id' : SignalId,
  'status' : Status,
  'strategy' : Strategy,
  'targetPrice' : IDL.Nat,
  'strikePrice' : IDL.Nat,
  'optionType' : OptionType,
  'stopLoss' : IDL.Nat,
  'timestamp' : Time,
  'entryPrice' : IDL.Nat,
  'expiry' : IDL.Text,
  'confidence' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const FetchResult = IDL.Record({
  'body' : IDL.Text,
  'isLive' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addSignal' : IDL.Func([Signal], [SignalId], []),
  'clearOldSignals' : IDL.Func([IDL.Nat], [], []),
  'fetchLiveOHLCV' : IDL.Func([IDL.Text, IDL.Text], [FetchResult], []),
  'fetchLiveQuotes' : IDL.Func(
      [],
      [IDL.Record({ 'body' : IDL.Text, 'isLive' : IDL.Bool })],
      [],
    ),
  'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getBySymbol' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
  'removeProfitBookedSignals' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSignalStatus' : IDL.Func([SignalId, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalId = IDL.Nat;
  const Status = IDL.Variant({
    'ProfitBooked' : IDL.Null,
    'Active' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const Strategy = IDL.Variant({
    'OI' : IDL.Null,
    'PCR' : IDL.Null,
    'RSI' : IDL.Null,
    'MACD' : IDL.Null,
    'News' : IDL.Null,
    'Volume' : IDL.Null,
    'Bollinger' : IDL.Null,
  });
  const OptionType = IDL.Variant({ 'CE' : IDL.Null, 'PE' : IDL.Null });
  const Time = IDL.Int;
  const Signal = IDL.Record({
    'id' : SignalId,
    'status' : Status,
    'strategy' : Strategy,
    'targetPrice' : IDL.Nat,
    'strikePrice' : IDL.Nat,
    'optionType' : OptionType,
    'stopLoss' : IDL.Nat,
    'timestamp' : Time,
    'entryPrice' : IDL.Nat,
    'expiry' : IDL.Text,
    'confidence' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const FetchResult = IDL.Record({ 'body' : IDL.Text, 'isLive' : IDL.Bool });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addSignal' : IDL.Func([Signal], [SignalId], []),
    'clearOldSignals' : IDL.Func([IDL.Nat], [], []),
    'fetchLiveOHLCV' : IDL.Func([IDL.Text, IDL.Text], [FetchResult], []),
    'fetchLiveQuotes' : IDL.Func(
        [],
        [IDL.Record({ 'body' : IDL.Text, 'isLive' : IDL.Bool })],
        [],
      ),
    'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getBySymbol' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
    'removeProfitBookedSignals' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSignalStatus' : IDL.Func([SignalId, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };