/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FetchResult { 'body' : string, 'isLive' : boolean }
export type OptionType = { 'CE' : null } |
  { 'PE' : null };
export interface Signal {
  'id' : SignalId,
  'status' : Status,
  'strategy' : Strategy,
  'targetPrice' : bigint,
  'strikePrice' : bigint,
  'optionType' : OptionType,
  'stopLoss' : bigint,
  'timestamp' : Time,
  'entryPrice' : bigint,
  'expiry' : string,
  'confidence' : bigint,
  'symbol' : string,
}
export type SignalId = bigint;
export type Status = { 'ProfitBooked' : null } |
  { 'Active' : null } |
  { 'Expired' : null };
export type Strategy = { 'OI' : null } |
  { 'PCR' : null } |
  { 'RSI' : null } |
  { 'MACD' : null } |
  { 'News' : null } |
  { 'Volume' : null } |
  { 'Bollinger' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addSignal' : ActorMethod<[Signal], SignalId>,
  'clearOldSignals' : ActorMethod<[bigint], undefined>,
  'fetchLiveOHLCV' : ActorMethod<[string, string], FetchResult>,
  'fetchLiveQuotes' : ActorMethod<[], { 'body' : string, 'isLive' : boolean }>,
  'getAllSignals' : ActorMethod<[], Array<Signal>>,
  'getBySymbol' : ActorMethod<[string], Array<Signal>>,
  'removeProfitBookedSignals' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSignalStatus' : ActorMethod<[SignalId, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];