/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: SignalId;
    status: Status;
    strategy: Strategy;
    targetPrice: bigint;
    strikePrice: bigint;
    optionType: OptionType;
    stopLoss: bigint;
    timestamp: Time;
    entryPrice: bigint;
    expiry: string;
    confidence: bigint;
    symbol: string;
}
export type SignalId = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface FetchResult {
    body: string;
    isLive: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum OptionType {
    CE = "CE",
    PE = "PE"
}
export enum Status {
    ProfitBooked = "ProfitBooked",
    Active = "Active",
    Expired = "Expired"
}
export enum Strategy {
    OI = "OI",
    PCR = "PCR",
    RSI = "RSI",
    MACD = "MACD",
    News = "News",
    Volume = "Volume",
    Bollinger = "Bollinger"
}
export interface backendInterface {
    addSignal(signal: Signal): Promise<SignalId>;
    clearOldSignals(days: bigint): Promise<void>;
    fetchLiveOHLCV(symbol: string, interval: string): Promise<FetchResult>;
    fetchLiveQuotes(): Promise<{
        body: string;
        isLive: boolean;
    }>;
    getAllSignals(): Promise<Array<Signal>>;
    getBySymbol(symbol: string): Promise<Array<Signal>>;
    removeProfitBookedSignals(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSignalStatus(id: SignalId, status: Status): Promise<void>;
}
import type { OptionType as _OptionType, Signal as _Signal, SignalId as _SignalId, Status as _Status, Strategy as _Strategy, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSignal(arg0: Signal): Promise<SignalId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignal(to_candid_Signal_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignal(to_candid_Signal_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearOldSignals(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOldSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOldSignals(arg0);
            return result;
        }
    }
    async fetchLiveOHLCV(arg0: string, arg1: string): Promise<FetchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchLiveOHLCV(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchLiveOHLCV(arg0, arg1);
            return result;
        }
    }
    async fetchLiveQuotes(): Promise<{
        body: string;
        isLive: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchLiveQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchLiveQuotes();
            return result;
        }
    }
    async getAllSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBySymbol(arg0: string): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBySymbol(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBySymbol(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeProfitBookedSignals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfitBookedSignals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfitBookedSignals();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSignalStatus(arg0: SignalId, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OptionType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OptionType): OptionType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SignalId;
    status: _Status;
    strategy: _Strategy;
    targetPrice: bigint;
    strikePrice: bigint;
    optionType: _OptionType;
    stopLoss: bigint;
    timestamp: _Time;
    entryPrice: bigint;
    expiry: string;
    confidence: bigint;
    symbol: string;
}): {
    id: SignalId;
    status: Status;
    strategy: Strategy;
    targetPrice: bigint;
    strikePrice: bigint;
    optionType: OptionType;
    stopLoss: bigint;
    timestamp: Time;
    entryPrice: bigint;
    expiry: string;
    confidence: bigint;
    symbol: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n12(_uploadFile, _downloadFile, value.status),
        strategy: from_candid_Strategy_n14(_uploadFile, _downloadFile, value.strategy),
        targetPrice: value.targetPrice,
        strikePrice: value.strikePrice,
        optionType: from_candid_OptionType_n16(_uploadFile, _downloadFile, value.optionType),
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        expiry: value.expiry,
        confidence: value.confidence,
        symbol: value.symbol
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ProfitBooked: null;
} | {
    Active: null;
} | {
    Expired: null;
}): Status {
    return "ProfitBooked" in value ? Status.ProfitBooked : "Active" in value ? Status.Active : "Expired" in value ? Status.Expired : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OI: null;
} | {
    PCR: null;
} | {
    RSI: null;
} | {
    MACD: null;
} | {
    News: null;
} | {
    Volume: null;
} | {
    Bollinger: null;
}): Strategy {
    return "OI" in value ? Strategy.OI : "PCR" in value ? Strategy.PCR : "RSI" in value ? Strategy.RSI : "MACD" in value ? Strategy.MACD : "News" in value ? Strategy.News : "Volume" in value ? Strategy.Volume : "Bollinger" in value ? Strategy.Bollinger : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CE: null;
} | {
    PE: null;
}): OptionType {
    return "CE" in value ? OptionType.CE : "PE" in value ? OptionType.PE : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n10(_uploadFile, _downloadFile, x));
}
function to_candid_OptionType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OptionType): _OptionType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Signal_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal): _Signal {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Strategy_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SignalId;
    status: Status;
    strategy: Strategy;
    targetPrice: bigint;
    strikePrice: bigint;
    optionType: OptionType;
    stopLoss: bigint;
    timestamp: Time;
    entryPrice: bigint;
    expiry: string;
    confidence: bigint;
    symbol: string;
}): {
    id: _SignalId;
    status: _Status;
    strategy: _Strategy;
    targetPrice: bigint;
    strikePrice: bigint;
    optionType: _OptionType;
    stopLoss: bigint;
    timestamp: _Time;
    entryPrice: bigint;
    expiry: string;
    confidence: bigint;
    symbol: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        strategy: to_candid_Strategy_n5(_uploadFile, _downloadFile, value.strategy),
        targetPrice: value.targetPrice,
        strikePrice: value.strikePrice,
        optionType: to_candid_OptionType_n7(_uploadFile, _downloadFile, value.optionType),
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        expiry: value.expiry,
        confidence: value.confidence,
        symbol: value.symbol
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    ProfitBooked: null;
} | {
    Active: null;
} | {
    Expired: null;
} {
    return value == Status.ProfitBooked ? {
        ProfitBooked: null
    } : value == Status.Active ? {
        Active: null
    } : value == Status.Expired ? {
        Expired: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): {
    OI: null;
} | {
    PCR: null;
} | {
    RSI: null;
} | {
    MACD: null;
} | {
    News: null;
} | {
    Volume: null;
} | {
    Bollinger: null;
} {
    return value == Strategy.OI ? {
        OI: null
    } : value == Strategy.PCR ? {
        PCR: null
    } : value == Strategy.RSI ? {
        RSI: null
    } : value == Strategy.MACD ? {
        MACD: null
    } : value == Strategy.News ? {
        News: null
    } : value == Strategy.Volume ? {
        Volume: null
    } : value == Strategy.Bollinger ? {
        Bollinger: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OptionType): {
    CE: null;
} | {
    PE: null;
} {
    return value == OptionType.CE ? {
        CE: null
    } : value == OptionType.PE ? {
        PE: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
